use_frameworks!

platform :ios, '9.0'

target 'MHOTCView_Example' do
  pod 'MHOTCView', :path => '../'
  pod 'Masonry'
  
  target 'MHOTCView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
